#!/usr/bin/env python

import logging
import argparse
import sys
import yaml
import os.path
import os
import subprocess
import fcntl

class Rclone(object):
    rclone = '/usr/bin/rclone'
    config = '/etc/bacula/rclone.conf'
    logFile = '/tmp/rclone.log'
    options = []

    @staticmethod
    def _exec_(*args):

        flags = Rclone.options + ['--config=%s' % Rclone.config, '--log-file=%s' % Rclone.logFile, '-q', '-c']
        logging.debug('Executing: %s %s %s' % (Rclone.rclone, ' '.join(flags),' '.join(args) ))

        output = open(os.devnull,'w')

        callList = [ Rclone.rclone ] + flags + __builtins__.list(args)
        r = subprocess.call(callList,stderr=output,stdout=output)
        
        if r != 0:
            raise Exception('Rclone command failed.  Check log' % Rclone.logFile )
        else:
            return True

    @staticmethod
    def copy(source,destination):
        return Rclone._exec_('copy',source,destination)

    @staticmethod
    def move(source,destination):
        return Rclone._exec_('move',source,destination)

    @staticmethod
    def ls(path):
        return Rclone._exec_('ls', path)

    @staticmethod
    def exists(path):
        try:
            Rclone._exec_('ls', path)
        except Exception: 
            return False

        return True

class State(object):
    loadedSlot = 0
    slots = 8192

class CommandOpts(object):
    changer = None
    command = None
    slot = None
    archive = None

    def __init__(self, params):
        self.changer = params.changerdevice
        self.slot = params.slot
        self.archive = params.archivedevice

def parseArgs(args):

    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)

    parser.add_argument('--lockfile', default='/var/lib/bacula/.rclonelock', 
        help='Lock file to prevent more than one rclone call from running and mucking up the state file')

    parser.add_argument('--logfile', default='/var/log/bacula/rclone-changer.log', 
        help='Where to store the rclone-changer log file (not the rclone log itself')

    parser.add_argument('--rclone_path', default='/usr/bin/rclone',
        help='Path to rclone binary')

    parser.add_argument('--rclone_options', default=False,
        help='All additional rclone options you need to pass in a single argument')

    parser.add_argument('--rclone_config', default='/etc/bacula/rclone.conf',
        help='Path to rclone config for your cloud storage of choice (result of `rclone config`)')

    parser.add_argument('--rclone_log', default='/tmp/rclone.log',
        help='Where to have rclone itself log to')

    parser.add_argument('--statefile', default='/var/lib/bacula/rclone-changer.state',
        help='Where to store our "changer" state')

    parser.add_argument('changerdevice')
    parser.add_argument('command')
    parser.add_argument('slot')
    parser.add_argument('archivedevice')

    return parser.parse_args()

def loaded(opts,state):
    print state.loadedSlot

def load(opts, state):
    logging.info("Loading volume %s into %s from %s" % (opts.slot,opts.archive,opts.changer))
    
    source = "/".join([opts.changer,opts.slot,os.path.basename(opts.archive)])
    destination = os.path.dirname(opts.archive)

    if state.loadedSlot != 0 and state.loadedSlot != opts.slot:
        logging.warning("Asked to load volume %s into %s but %s is loaded.  Unloading %s" % 
            (opts.slot,opts.archive,state.loadedSlot,state.loadedSlot))

        unloadOpts = argparse.Namespace()
        unloadOpts.slot = state.loadedSlot
        unloadOpts.archive = opts.archive
        unloadOpts.changer = opts.changer
        unload(unloadOpts, state)
    
    if state.loadedSlot == opts.slot:    
        logging.info("Volume %s already loaded at %s from %s" % (opts.slot,opts.archive,opts.changer))
        return

    logging.info("Copying %s to %s for load" % (source, destination))

    if Rclone.exists(source):
        Rclone.copy(source,destination)
    else:
        logging.warning("Volume %s didn't exist in %s.  Creating a new file" % (opts.slot, opts.changer))
        os.unlink(opts.archive)
        open(opts.archive,'w').close()
    
    state.loadedSlot = opts.slot
    logging.info("Loaded volume %s into %s from %s" % (opts.slot,opts.archive,opts.changer))

def unload(opts, state):
    logging.info("Unloading volume %s to %s from %s" % (opts.slot,opts.changer,opts.archive))

    source = opts.archive
    destination = "/".join([opts.changer,opts.slot])
  
    if opts.slot == state.loadedSlot:
        try:
            Rclone.copy(source, destination)
            state.loadedSlot = 0
            logging.info("Unloaded volume %s to %s from %s" % (opts.slot, opts.changer, opts.archive))
        except Exception as e:
            logging.error("Failed to unload volume %s: %s" % (opts.slot, e))

    else: 
        logging.error("Asked to unload volume %s but loaded volume is %s" % (opts.slot, state.loadedSlot))
        raise Exception("Volume %s not loaded" % opts.slot)

def list(opts, state):
    logging.info("Listing volumes in %s" % opts.changer)
    for x in range(1,state.slots + 1):
        print "{0}:VTAPE-{0:05n}".format(x)

def slots(opts, state):
    print state.slots

def dispatch(command, commandOpts, state):
    dispatch = {
     'loaded': loaded,
     'load': load,
     'unload': unload,
     'list': list,
     'slots': slots,
    }

    dispatch[command](commandOpts, state)


if __name__ == "__main__":
    config = parseArgs(sys.argv)

    logging.basicConfig(filename=config.logfile, level=logging.DEBUG, format='%(asctime)s - %(levelname)s - %(message)s')
    logging.debug("Starting with args: %s" % vars(config))
    logging.info("Loading state from %s" % config.statefile)

    logging.debug("Locking at '%s'" % config.lockfile)
    lockF = open(config.lockfile,'w')
    fcntl.lockf(lockF, fcntl.LOCK_EX)

    try:
        stateF = open(config.statefile)
        fcntl.flock(stateF, fcntl.LOCK_EX)
        state = yaml.load(stateF)
        stateF.close()

    except IOError as e:
        logging.warning("State file not present.  Starting from scratch and assuming no loaded volumes: %s" % e)
        state = State()

    commandOpts = CommandOpts(config)

    Rclone.config = config.rclone_config
    Rclone.rclone = config.rclone_path
    if config.rclone_options:
        Rclone.options = str(config.rclone_options).split(' ')
    Rclone.logFile = config.rclone_log

    Rclone.localFile = config.archivedevice
    
    dispatch(config.command, commandOpts, state)

    stateF = open(config.statefile,'w')
    fcntl.lockf(stateF, fcntl.LOCK_EX)
    yaml.dump(state, stateF, default_flow_style=False)
    stateF.close()









